class CoinModel {
  final String market,
      opening_price,
      high_price,
      low_price,
      trade_price,
      prev_closing_price,
      trade_date,
      trade_time,
      trade_date_kst,
      trade_time_kst,
      trade_timestamp,
      change,
      change_price,
      change_rate,
      signed_change_price,
      signed_change_rate,
      trade_volume,
      acc_trade_price_24h,
      acc_trade_volume,
      acc_trade_volume_24h,
      highest_52_week_price,
      highest_52_week_date,
      lowest_52_week_price,
      lowest_52_week_date,
      timestamp;
  CoinModel.fromJson(Map<String, dynamic> json)
      : market = json['market'],
        trade_date = json['trade_date'],
        trade_time = json['trade_time'],
        trade_date_kst = json['trade_date_kst'],
        trade_time_kst = json['trade_time_kst'],
        trade_timestamp = json['trade_timestamp'],
        opening_price = json['opening_price'],
        high_price = json['high_price'],
        low_price = json['low_price'],
        trade_price = json['trade_price'],
        prev_closing_price = json['prev_closing_price'],
        change = json['change'],
        change_price = json['change_price'],
        change_rate = json['change_rate'],
        signed_change_price = json['signed_change_price'],
        signed_change_rate = json['signed_change_rate'],
        trade_volume = json['trade_volume'],
        acc_trade_price_24h = json['acc_trade_price_24h'],
        acc_trade_volume = json['acc_trade_volume'],
        acc_trade_volume_24h = json['acc_trade_volume_24h'],
        highest_52_week_price = json['highest_52_week_price'],
        highest_52_week_date = json['highest_52_week_date'],
        lowest_52_week_price = json['lowest_52_week_price'],
        lowest_52_week_date = json['lowest_52_week_date'],
        timestamp = json['timestamp'];
}
