// To parse this JSON data, do
//
//     final coinList = coinListFromJson(jsonString);

import 'dart:convert';

CoinList coinListFromJson(String str) => CoinList.fromJson(json.decode(str));

String coinListToJson(CoinList data) => json.encode(data.toJson());

class CoinList {
  String status;
  Data data;

  CoinList({
    required this.status,
    required this.data,
  });

  factory CoinList.fromJson(Map<String, dynamic> json) => CoinList(
        status: json["status"],
        data: Data.fromJson(json["data"]),
      );

  Map<String, dynamic> toJson() => {
        "status": status,
        "data": data.toJson(),
      };
}

class Data {
  The1Inch btc;
  The1Inch eth;
  The1Inch etc;
  The1Inch xrp;
  The1Inch bch;
  The1Inch qtum;
  The1Inch btg;
  The1Inch eos;
  The1Inch icx;
  The1Inch trx;
  The1Inch elf;
  The1Inch knc;
  The1Inch glm;
  The1Inch zil;
  The1Inch waxp;
  The1Inch powr;
  The1Inch lrc;
  The1Inch steem;
  The1Inch zrx;
  The1Inch snt;
  The1Inch ada;
  The1Inch ctxc;
  The1Inch bat;
  The1Inch theta;
  The1Inch loom;
  The1Inch cvc;
  The1Inch waves;
  The1Inch link;
  The1Inch enj;
  The1Inch vet;
  The1Inch mtl;
  The1Inch iost;
  The1Inch amo;
  The1Inch bsv;
  The1Inch orbs;
  The1Inch tfuel;
  The1Inch valor;
  The1Inch con;
  The1Inch ankr;
  The1Inch mix;
  The1Inch cro;
  The1Inch fx;
  The1Inch chr;
  The1Inch mbl;
  The1Inch mxc;
  The1Inch fct2;
  The1Inch wom;
  The1Inch boa;
  The1Inch mev;
  The1Inch sxp;
  The1Inch cos;
  The1Inch el;
  The1Inch hive;
  The1Inch xpr;
  The1Inch vra;
  The1Inch fit;
  The1Inch egg;
  The1Inch bora;
  The1Inch arpa;
  The1Inch ctc;
  The1Inch apm;
  The1Inch ckb;
  The1Inch aergo;
  The1Inch evz;
  The1Inch qtcon;
  The1Inch uni;
  The1Inch yfi;
  The1Inch uma;
  The1Inch aave;
  The1Inch comp;
  The1Inch bal;
  The1Inch rsr;
  The1Inch nmr;
  The1Inch rlc;
  The1Inch uos;
  The1Inch sand;
  The1Inch stpt;
  The1Inch bel;
  The1Inch obsr;
  The1Inch pola;
  The1Inch adp;
  The1Inch dvi;
  The1Inch ghx;
  The1Inch mvc;
  The1Inch bly;
  The1Inch grt;
  The1Inch biot;
  The1Inch snx;
  The1Inch sofi;
  The1Inch gracy;
  The1Inch oxt;
  The1Inch map;
  The1Inch aqt;
  The1Inch wiken;
  The1Inch ctsi;
  The1Inch mana;
  The1Inch lpt;
  The1Inch mkr;
  The1Inch sushi;
  The1Inch asm;
  The1Inch pundix;
  The1Inch celr;
  The1Inch front;
  The1Inch rly;
  The1Inch ocean;
  The1Inch bfc;
  The1Inch alice;
  The1Inch ogn;
  The1Inch coti;
  The1Inch cake;
  The1Inch bnt;
  The1Inch xvs;
  The1Inch swap;
  The1Inch chz;
  The1Inch axs;
  The1Inch dao;
  The1Inch six;
  The1Inch dai;
  The1Inch shib;
  The1Inch matic;
  The1Inch woo;
  The1Inch ach;
  The1Inch xlm;
  The1Inch ont;
  The1Inch meta;
  The1Inch klay;
  The1Inch ong;
  The1Inch algo;
  The1Inch jst;
  The1Inch xtz;
  The1Inch mlk;
  The1Inch dot;
  The1Inch atom;
  The1Inch temco;
  The1Inch doge;
  The1Inch ksm;
  The1Inch ctk;
  The1Inch bnb;
  The1Inch nft;
  The1Inch sun;
  The1Inch xec;
  The1Inch agix;
  The1Inch sol;
  The1Inch fnsa;
  The1Inch egld;
  The1Inch mask;
  The1Inch c98;
  The1Inch med;
  The1Inch the1Inch;
  The1Inch crv;
  The1Inch boba;
  The1Inch dydx;
  The1Inch mina;
  The1Inch flow;
  The1Inch joe;
  The1Inch gala;
  The1Inch btt;
  The1Inch jasmy;
  The1Inch req;
  The1Inch cspr;
  The1Inch avax;
  The1Inch tdrop;
  The1Inch hbar;
  The1Inch fanc;
  The1Inch npt;
  The1Inch rei;
  The1Inch t;
  The1Inch mbx;
  The1Inch gmt;
  The1Inch tava;
  The1Inch dar;
  The1Inch ape;
  The1Inch wncg;
  The1Inch alt;
  The1Inch xcn;
  The1Inch azit;
  The1Inch flr;
  The1Inch sfp;
  The1Inch fitfi;
  The1Inch stat;
  The1Inch crts;
  The1Inch vix;
  The1Inch lbl;
  The1Inch flz;
  The1Inch lm;
  The1Inch grnd;
  The1Inch apt;
  The1Inch blur;
  The1Inch wemix;
  The1Inch oas;
  The1Inch hook;
  The1Inch entc;
  The1Inch onit;
  The1Inch op;
  The1Inch roa;
  The1Inch gmx;
  The1Inch stx;
  The1Inch xpla;
  The1Inch arb;
  The1Inch inj;
  The1Inch hft;
  The1Inch rpl;
  The1Inch imx;
  The1Inch cfx;
  The1Inch acs;
  The1Inch fxs;
  The1Inch celo;
  The1Inch ldo;
  The1Inch ftm;
  The1Inch fet;
  The1Inch sui;
  The1Inch nct;
  The1Inch floki;
  The1Inch alex;
  The1Inch id;
  The1Inch rndr;
  The1Inch stg;
  The1Inch osmo;
  The1Inch gal;
  The1Inch ilv;
  The1Inch mav;
  The1Inch rss3;
  The1Inch audio;
  The1Inch agi;
  The1Inch rdnt;
  The1Inch astr;
  The1Inch wld;
  The1Inch flux;
  The1Inch rvn;
  The1Inch lever;
  The1Inch edu;
  The1Inch sei;
  The1Inch waxl;
  The1Inch moc;
  The1Inch pepe;
  The1Inch cyber;
  The1Inch arkm;
  The1Inch pyr;
  The1Inch iotx;
  The1Inch high;
  The1Inch pendle;
  The1Inch storj;
  The1Inch api3;
  The1Inch ztx;
  The1Inch mnt;
  The1Inch gtc;
  The1Inch tia;
  The1Inch zbc;
  The1Inch spurs;
  The1Inch neo;
  The1Inch gas;
  The1Inch hifi;
  The1Inch bigtime;
  The1Inch grs;
  The1Inch ark;
  The1Inch ygg;
  The1Inch hunt;
  The1Inch kava;
  The1Inch stmx;
  The1Inch magic;
  The1Inch usdt;
  The1Inch usdc;
  The1Inch rad;
  The1Inch lsk;
  The1Inch tt;
  The1Inch ace;
  The1Inch iq;
  The1Inch pyth;
  The1Inch manta;
  The1Inch jup;
  The1Inch strk;
  The1Inch sc;
  The1Inch strax;
  String date;

  Data({
    required this.btc,
    required this.eth,
    required this.etc,
    required this.xrp,
    required this.bch,
    required this.qtum,
    required this.btg,
    required this.eos,
    required this.icx,
    required this.trx,
    required this.elf,
    required this.knc,
    required this.glm,
    required this.zil,
    required this.waxp,
    required this.powr,
    required this.lrc,
    required this.steem,
    required this.zrx,
    required this.snt,
    required this.ada,
    required this.ctxc,
    required this.bat,
    required this.theta,
    required this.loom,
    required this.cvc,
    required this.waves,
    required this.link,
    required this.enj,
    required this.vet,
    required this.mtl,
    required this.iost,
    required this.amo,
    required this.bsv,
    required this.orbs,
    required this.tfuel,
    required this.valor,
    required this.con,
    required this.ankr,
    required this.mix,
    required this.cro,
    required this.fx,
    required this.chr,
    required this.mbl,
    required this.mxc,
    required this.fct2,
    required this.wom,
    required this.boa,
    required this.mev,
    required this.sxp,
    required this.cos,
    required this.el,
    required this.hive,
    required this.xpr,
    required this.vra,
    required this.fit,
    required this.egg,
    required this.bora,
    required this.arpa,
    required this.ctc,
    required this.apm,
    required this.ckb,
    required this.aergo,
    required this.evz,
    required this.qtcon,
    required this.uni,
    required this.yfi,
    required this.uma,
    required this.aave,
    required this.comp,
    required this.bal,
    required this.rsr,
    required this.nmr,
    required this.rlc,
    required this.uos,
    required this.sand,
    required this.stpt,
    required this.bel,
    required this.obsr,
    required this.pola,
    required this.adp,
    required this.dvi,
    required this.ghx,
    required this.mvc,
    required this.bly,
    required this.grt,
    required this.biot,
    required this.snx,
    required this.sofi,
    required this.gracy,
    required this.oxt,
    required this.map,
    required this.aqt,
    required this.wiken,
    required this.ctsi,
    required this.mana,
    required this.lpt,
    required this.mkr,
    required this.sushi,
    required this.asm,
    required this.pundix,
    required this.celr,
    required this.front,
    required this.rly,
    required this.ocean,
    required this.bfc,
    required this.alice,
    required this.ogn,
    required this.coti,
    required this.cake,
    required this.bnt,
    required this.xvs,
    required this.swap,
    required this.chz,
    required this.axs,
    required this.dao,
    required this.six,
    required this.dai,
    required this.shib,
    required this.matic,
    required this.woo,
    required this.ach,
    required this.xlm,
    required this.ont,
    required this.meta,
    required this.klay,
    required this.ong,
    required this.algo,
    required this.jst,
    required this.xtz,
    required this.mlk,
    required this.dot,
    required this.atom,
    required this.temco,
    required this.doge,
    required this.ksm,
    required this.ctk,
    required this.bnb,
    required this.nft,
    required this.sun,
    required this.xec,
    required this.agix,
    required this.sol,
    required this.fnsa,
    required this.egld,
    required this.mask,
    required this.c98,
    required this.med,
    required this.the1Inch,
    required this.crv,
    required this.boba,
    required this.dydx,
    required this.mina,
    required this.flow,
    required this.joe,
    required this.gala,
    required this.btt,
    required this.jasmy,
    required this.req,
    required this.cspr,
    required this.avax,
    required this.tdrop,
    required this.hbar,
    required this.fanc,
    required this.npt,
    required this.rei,
    required this.t,
    required this.mbx,
    required this.gmt,
    required this.tava,
    required this.dar,
    required this.ape,
    required this.wncg,
    required this.alt,
    required this.xcn,
    required this.azit,
    required this.flr,
    required this.sfp,
    required this.fitfi,
    required this.stat,
    required this.crts,
    required this.vix,
    required this.lbl,
    required this.flz,
    required this.lm,
    required this.grnd,
    required this.apt,
    required this.blur,
    required this.wemix,
    required this.oas,
    required this.hook,
    required this.entc,
    required this.onit,
    required this.op,
    required this.roa,
    required this.gmx,
    required this.stx,
    required this.xpla,
    required this.arb,
    required this.inj,
    required this.hft,
    required this.rpl,
    required this.imx,
    required this.cfx,
    required this.acs,
    required this.fxs,
    required this.celo,
    required this.ldo,
    required this.ftm,
    required this.fet,
    required this.sui,
    required this.nct,
    required this.floki,
    required this.alex,
    required this.id,
    required this.rndr,
    required this.stg,
    required this.osmo,
    required this.gal,
    required this.ilv,
    required this.mav,
    required this.rss3,
    required this.audio,
    required this.agi,
    required this.rdnt,
    required this.astr,
    required this.wld,
    required this.flux,
    required this.rvn,
    required this.lever,
    required this.edu,
    required this.sei,
    required this.waxl,
    required this.moc,
    required this.pepe,
    required this.cyber,
    required this.arkm,
    required this.pyr,
    required this.iotx,
    required this.high,
    required this.pendle,
    required this.storj,
    required this.api3,
    required this.ztx,
    required this.mnt,
    required this.gtc,
    required this.tia,
    required this.zbc,
    required this.spurs,
    required this.neo,
    required this.gas,
    required this.hifi,
    required this.bigtime,
    required this.grs,
    required this.ark,
    required this.ygg,
    required this.hunt,
    required this.kava,
    required this.stmx,
    required this.magic,
    required this.usdt,
    required this.usdc,
    required this.rad,
    required this.lsk,
    required this.tt,
    required this.ace,
    required this.iq,
    required this.pyth,
    required this.manta,
    required this.jup,
    required this.strk,
    required this.sc,
    required this.strax,
    required this.date,
  });

  factory Data.fromJson(Map<String, dynamic> json) => Data(
        btc: The1Inch.fromJson(json["BTC"]),
        eth: The1Inch.fromJson(json["ETH"]),
        etc: The1Inch.fromJson(json["ETC"]),
        xrp: The1Inch.fromJson(json["XRP"]),
        bch: The1Inch.fromJson(json["BCH"]),
        qtum: The1Inch.fromJson(json["QTUM"]),
        btg: The1Inch.fromJson(json["BTG"]),
        eos: The1Inch.fromJson(json["EOS"]),
        icx: The1Inch.fromJson(json["ICX"]),
        trx: The1Inch.fromJson(json["TRX"]),
        elf: The1Inch.fromJson(json["ELF"]),
        knc: The1Inch.fromJson(json["KNC"]),
        glm: The1Inch.fromJson(json["GLM"]),
        zil: The1Inch.fromJson(json["ZIL"]),
        waxp: The1Inch.fromJson(json["WAXP"]),
        powr: The1Inch.fromJson(json["POWR"]),
        lrc: The1Inch.fromJson(json["LRC"]),
        steem: The1Inch.fromJson(json["STEEM"]),
        zrx: The1Inch.fromJson(json["ZRX"]),
        snt: The1Inch.fromJson(json["SNT"]),
        ada: The1Inch.fromJson(json["ADA"]),
        ctxc: The1Inch.fromJson(json["CTXC"]),
        bat: The1Inch.fromJson(json["BAT"]),
        theta: The1Inch.fromJson(json["THETA"]),
        loom: The1Inch.fromJson(json["LOOM"]),
        cvc: The1Inch.fromJson(json["CVC"]),
        waves: The1Inch.fromJson(json["WAVES"]),
        link: The1Inch.fromJson(json["LINK"]),
        enj: The1Inch.fromJson(json["ENJ"]),
        vet: The1Inch.fromJson(json["VET"]),
        mtl: The1Inch.fromJson(json["MTL"]),
        iost: The1Inch.fromJson(json["IOST"]),
        amo: The1Inch.fromJson(json["AMO"]),
        bsv: The1Inch.fromJson(json["BSV"]),
        orbs: The1Inch.fromJson(json["ORBS"]),
        tfuel: The1Inch.fromJson(json["TFUEL"]),
        valor: The1Inch.fromJson(json["VALOR"]),
        con: The1Inch.fromJson(json["CON"]),
        ankr: The1Inch.fromJson(json["ANKR"]),
        mix: The1Inch.fromJson(json["MIX"]),
        cro: The1Inch.fromJson(json["CRO"]),
        fx: The1Inch.fromJson(json["FX"]),
        chr: The1Inch.fromJson(json["CHR"]),
        mbl: The1Inch.fromJson(json["MBL"]),
        mxc: The1Inch.fromJson(json["MXC"]),
        fct2: The1Inch.fromJson(json["FCT2"]),
        wom: The1Inch.fromJson(json["WOM"]),
        boa: The1Inch.fromJson(json["BOA"]),
        mev: The1Inch.fromJson(json["MEV"]),
        sxp: The1Inch.fromJson(json["SXP"]),
        cos: The1Inch.fromJson(json["COS"]),
        el: The1Inch.fromJson(json["EL"]),
        hive: The1Inch.fromJson(json["HIVE"]),
        xpr: The1Inch.fromJson(json["XPR"]),
        vra: The1Inch.fromJson(json["VRA"]),
        fit: The1Inch.fromJson(json["FIT"]),
        egg: The1Inch.fromJson(json["EGG"]),
        bora: The1Inch.fromJson(json["BORA"]),
        arpa: The1Inch.fromJson(json["ARPA"]),
        ctc: The1Inch.fromJson(json["CTC"]),
        apm: The1Inch.fromJson(json["APM"]),
        ckb: The1Inch.fromJson(json["CKB"]),
        aergo: The1Inch.fromJson(json["AERGO"]),
        evz: The1Inch.fromJson(json["EVZ"]),
        qtcon: The1Inch.fromJson(json["QTCON"]),
        uni: The1Inch.fromJson(json["UNI"]),
        yfi: The1Inch.fromJson(json["YFI"]),
        uma: The1Inch.fromJson(json["UMA"]),
        aave: The1Inch.fromJson(json["AAVE"]),
        comp: The1Inch.fromJson(json["COMP"]),
        bal: The1Inch.fromJson(json["BAL"]),
        rsr: The1Inch.fromJson(json["RSR"]),
        nmr: The1Inch.fromJson(json["NMR"]),
        rlc: The1Inch.fromJson(json["RLC"]),
        uos: The1Inch.fromJson(json["UOS"]),
        sand: The1Inch.fromJson(json["SAND"]),
        stpt: The1Inch.fromJson(json["STPT"]),
        bel: The1Inch.fromJson(json["BEL"]),
        obsr: The1Inch.fromJson(json["OBSR"]),
        pola: The1Inch.fromJson(json["POLA"]),
        adp: The1Inch.fromJson(json["ADP"]),
        dvi: The1Inch.fromJson(json["DVI"]),
        ghx: The1Inch.fromJson(json["GHX"]),
        mvc: The1Inch.fromJson(json["MVC"]),
        bly: The1Inch.fromJson(json["BLY"]),
        grt: The1Inch.fromJson(json["GRT"]),
        biot: The1Inch.fromJson(json["BIOT"]),
        snx: The1Inch.fromJson(json["SNX"]),
        sofi: The1Inch.fromJson(json["SOFI"]),
        gracy: The1Inch.fromJson(json["GRACY"]),
        oxt: The1Inch.fromJson(json["OXT"]),
        map: The1Inch.fromJson(json["MAP"]),
        aqt: The1Inch.fromJson(json["AQT"]),
        wiken: The1Inch.fromJson(json["WIKEN"]),
        ctsi: The1Inch.fromJson(json["CTSI"]),
        mana: The1Inch.fromJson(json["MANA"]),
        lpt: The1Inch.fromJson(json["LPT"]),
        mkr: The1Inch.fromJson(json["MKR"]),
        sushi: The1Inch.fromJson(json["SUSHI"]),
        asm: The1Inch.fromJson(json["ASM"]),
        pundix: The1Inch.fromJson(json["PUNDIX"]),
        celr: The1Inch.fromJson(json["CELR"]),
        front: The1Inch.fromJson(json["FRONT"]),
        rly: The1Inch.fromJson(json["RLY"]),
        ocean: The1Inch.fromJson(json["OCEAN"]),
        bfc: The1Inch.fromJson(json["BFC"]),
        alice: The1Inch.fromJson(json["ALICE"]),
        ogn: The1Inch.fromJson(json["OGN"]),
        coti: The1Inch.fromJson(json["COTI"]),
        cake: The1Inch.fromJson(json["CAKE"]),
        bnt: The1Inch.fromJson(json["BNT"]),
        xvs: The1Inch.fromJson(json["XVS"]),
        swap: The1Inch.fromJson(json["SWAP"]),
        chz: The1Inch.fromJson(json["CHZ"]),
        axs: The1Inch.fromJson(json["AXS"]),
        dao: The1Inch.fromJson(json["DAO"]),
        six: The1Inch.fromJson(json["SIX"]),
        dai: The1Inch.fromJson(json["DAI"]),
        shib: The1Inch.fromJson(json["SHIB"]),
        matic: The1Inch.fromJson(json["MATIC"]),
        woo: The1Inch.fromJson(json["WOO"]),
        ach: The1Inch.fromJson(json["ACH"]),
        xlm: The1Inch.fromJson(json["XLM"]),
        ont: The1Inch.fromJson(json["ONT"]),
        meta: The1Inch.fromJson(json["META"]),
        klay: The1Inch.fromJson(json["KLAY"]),
        ong: The1Inch.fromJson(json["ONG"]),
        algo: The1Inch.fromJson(json["ALGO"]),
        jst: The1Inch.fromJson(json["JST"]),
        xtz: The1Inch.fromJson(json["XTZ"]),
        mlk: The1Inch.fromJson(json["MLK"]),
        dot: The1Inch.fromJson(json["DOT"]),
        atom: The1Inch.fromJson(json["ATOM"]),
        temco: The1Inch.fromJson(json["TEMCO"]),
        doge: The1Inch.fromJson(json["DOGE"]),
        ksm: The1Inch.fromJson(json["KSM"]),
        ctk: The1Inch.fromJson(json["CTK"]),
        bnb: The1Inch.fromJson(json["BNB"]),
        nft: The1Inch.fromJson(json["NFT"]),
        sun: The1Inch.fromJson(json["SUN"]),
        xec: The1Inch.fromJson(json["XEC"]),
        agix: The1Inch.fromJson(json["AGIX"]),
        sol: The1Inch.fromJson(json["SOL"]),
        fnsa: The1Inch.fromJson(json["FNSA"]),
        egld: The1Inch.fromJson(json["EGLD"]),
        mask: The1Inch.fromJson(json["MASK"]),
        c98: The1Inch.fromJson(json["C98"]),
        med: The1Inch.fromJson(json["MED"]),
        the1Inch: The1Inch.fromJson(json["1INCH"]),
        crv: The1Inch.fromJson(json["CRV"]),
        boba: The1Inch.fromJson(json["BOBA"]),
        dydx: The1Inch.fromJson(json["DYDX"]),
        mina: The1Inch.fromJson(json["MINA"]),
        flow: The1Inch.fromJson(json["FLOW"]),
        joe: The1Inch.fromJson(json["JOE"]),
        gala: The1Inch.fromJson(json["GALA"]),
        btt: The1Inch.fromJson(json["BTT"]),
        jasmy: The1Inch.fromJson(json["JASMY"]),
        req: The1Inch.fromJson(json["REQ"]),
        cspr: The1Inch.fromJson(json["CSPR"]),
        avax: The1Inch.fromJson(json["AVAX"]),
        tdrop: The1Inch.fromJson(json["TDROP"]),
        hbar: The1Inch.fromJson(json["HBAR"]),
        fanc: The1Inch.fromJson(json["FANC"]),
        npt: The1Inch.fromJson(json["NPT"]),
        rei: The1Inch.fromJson(json["REI"]),
        t: The1Inch.fromJson(json["T"]),
        mbx: The1Inch.fromJson(json["MBX"]),
        gmt: The1Inch.fromJson(json["GMT"]),
        tava: The1Inch.fromJson(json["TAVA"]),
        dar: The1Inch.fromJson(json["DAR"]),
        ape: The1Inch.fromJson(json["APE"]),
        wncg: The1Inch.fromJson(json["WNCG"]),
        alt: The1Inch.fromJson(json["ALT"]),
        xcn: The1Inch.fromJson(json["XCN"]),
        azit: The1Inch.fromJson(json["AZIT"]),
        flr: The1Inch.fromJson(json["FLR"]),
        sfp: The1Inch.fromJson(json["SFP"]),
        fitfi: The1Inch.fromJson(json["FITFI"]),
        stat: The1Inch.fromJson(json["STAT"]),
        crts: The1Inch.fromJson(json["CRTS"]),
        vix: The1Inch.fromJson(json["VIX"]),
        lbl: The1Inch.fromJson(json["LBL"]),
        flz: The1Inch.fromJson(json["FLZ"]),
        lm: The1Inch.fromJson(json["LM"]),
        grnd: The1Inch.fromJson(json["GRND"]),
        apt: The1Inch.fromJson(json["APT"]),
        blur: The1Inch.fromJson(json["BLUR"]),
        wemix: The1Inch.fromJson(json["WEMIX"]),
        oas: The1Inch.fromJson(json["OAS"]),
        hook: The1Inch.fromJson(json["HOOK"]),
        entc: The1Inch.fromJson(json["ENTC"]),
        onit: The1Inch.fromJson(json["ONIT"]),
        op: The1Inch.fromJson(json["OP"]),
        roa: The1Inch.fromJson(json["ROA"]),
        gmx: The1Inch.fromJson(json["GMX"]),
        stx: The1Inch.fromJson(json["STX"]),
        xpla: The1Inch.fromJson(json["XPLA"]),
        arb: The1Inch.fromJson(json["ARB"]),
        inj: The1Inch.fromJson(json["INJ"]),
        hft: The1Inch.fromJson(json["HFT"]),
        rpl: The1Inch.fromJson(json["RPL"]),
        imx: The1Inch.fromJson(json["IMX"]),
        cfx: The1Inch.fromJson(json["CFX"]),
        acs: The1Inch.fromJson(json["ACS"]),
        fxs: The1Inch.fromJson(json["FXS"]),
        celo: The1Inch.fromJson(json["CELO"]),
        ldo: The1Inch.fromJson(json["LDO"]),
        ftm: The1Inch.fromJson(json["FTM"]),
        fet: The1Inch.fromJson(json["FET"]),
        sui: The1Inch.fromJson(json["SUI"]),
        nct: The1Inch.fromJson(json["NCT"]),
        floki: The1Inch.fromJson(json["FLOKI"]),
        alex: The1Inch.fromJson(json["ALEX"]),
        id: The1Inch.fromJson(json["ID"]),
        rndr: The1Inch.fromJson(json["RNDR"]),
        stg: The1Inch.fromJson(json["STG"]),
        osmo: The1Inch.fromJson(json["OSMO"]),
        gal: The1Inch.fromJson(json["GAL"]),
        ilv: The1Inch.fromJson(json["ILV"]),
        mav: The1Inch.fromJson(json["MAV"]),
        rss3: The1Inch.fromJson(json["RSS3"]),
        audio: The1Inch.fromJson(json["AUDIO"]),
        agi: The1Inch.fromJson(json["AGI"]),
        rdnt: The1Inch.fromJson(json["RDNT"]),
        astr: The1Inch.fromJson(json["ASTR"]),
        wld: The1Inch.fromJson(json["WLD"]),
        flux: The1Inch.fromJson(json["FLUX"]),
        rvn: The1Inch.fromJson(json["RVN"]),
        lever: The1Inch.fromJson(json["LEVER"]),
        edu: The1Inch.fromJson(json["EDU"]),
        sei: The1Inch.fromJson(json["SEI"]),
        waxl: The1Inch.fromJson(json["WAXL"]),
        moc: The1Inch.fromJson(json["MOC"]),
        pepe: The1Inch.fromJson(json["PEPE"]),
        cyber: The1Inch.fromJson(json["CYBER"]),
        arkm: The1Inch.fromJson(json["ARKM"]),
        pyr: The1Inch.fromJson(json["PYR"]),
        iotx: The1Inch.fromJson(json["IOTX"]),
        high: The1Inch.fromJson(json["HIGH"]),
        pendle: The1Inch.fromJson(json["PENDLE"]),
        storj: The1Inch.fromJson(json["STORJ"]),
        api3: The1Inch.fromJson(json["API3"]),
        ztx: The1Inch.fromJson(json["ZTX"]),
        mnt: The1Inch.fromJson(json["MNT"]),
        gtc: The1Inch.fromJson(json["GTC"]),
        tia: The1Inch.fromJson(json["TIA"]),
        zbc: The1Inch.fromJson(json["ZBC"]),
        spurs: The1Inch.fromJson(json["SPURS"]),
        neo: The1Inch.fromJson(json["NEO"]),
        gas: The1Inch.fromJson(json["GAS"]),
        hifi: The1Inch.fromJson(json["HIFI"]),
        bigtime: The1Inch.fromJson(json["BIGTIME"]),
        grs: The1Inch.fromJson(json["GRS"]),
        ark: The1Inch.fromJson(json["ARK"]),
        ygg: The1Inch.fromJson(json["YGG"]),
        hunt: The1Inch.fromJson(json["HUNT"]),
        kava: The1Inch.fromJson(json["KAVA"]),
        stmx: The1Inch.fromJson(json["STMX"]),
        magic: The1Inch.fromJson(json["MAGIC"]),
        usdt: The1Inch.fromJson(json["USDT"]),
        usdc: The1Inch.fromJson(json["USDC"]),
        rad: The1Inch.fromJson(json["RAD"]),
        lsk: The1Inch.fromJson(json["LSK"]),
        tt: The1Inch.fromJson(json["TT"]),
        ace: The1Inch.fromJson(json["ACE"]),
        iq: The1Inch.fromJson(json["IQ"]),
        pyth: The1Inch.fromJson(json["PYTH"]),
        manta: The1Inch.fromJson(json["MANTA"]),
        jup: The1Inch.fromJson(json["JUP"]),
        strk: The1Inch.fromJson(json["STRK"]),
        sc: The1Inch.fromJson(json["SC"]),
        strax: The1Inch.fromJson(json["STRAX"]),
        date: json["date"],
      );

  Map<String, dynamic> toJson() => {
        "BTC": btc.toJson(),
        "ETH": eth.toJson(),
        "ETC": etc.toJson(),
        "XRP": xrp.toJson(),
        "BCH": bch.toJson(),
        "QTUM": qtum.toJson(),
        "BTG": btg.toJson(),
        "EOS": eos.toJson(),
        "ICX": icx.toJson(),
        "TRX": trx.toJson(),
        "ELF": elf.toJson(),
        "KNC": knc.toJson(),
        "GLM": glm.toJson(),
        "ZIL": zil.toJson(),
        "WAXP": waxp.toJson(),
        "POWR": powr.toJson(),
        "LRC": lrc.toJson(),
        "STEEM": steem.toJson(),
        "ZRX": zrx.toJson(),
        "SNT": snt.toJson(),
        "ADA": ada.toJson(),
        "CTXC": ctxc.toJson(),
        "BAT": bat.toJson(),
        "THETA": theta.toJson(),
        "LOOM": loom.toJson(),
        "CVC": cvc.toJson(),
        "WAVES": waves.toJson(),
        "LINK": link.toJson(),
        "ENJ": enj.toJson(),
        "VET": vet.toJson(),
        "MTL": mtl.toJson(),
        "IOST": iost.toJson(),
        "AMO": amo.toJson(),
        "BSV": bsv.toJson(),
        "ORBS": orbs.toJson(),
        "TFUEL": tfuel.toJson(),
        "VALOR": valor.toJson(),
        "CON": con.toJson(),
        "ANKR": ankr.toJson(),
        "MIX": mix.toJson(),
        "CRO": cro.toJson(),
        "FX": fx.toJson(),
        "CHR": chr.toJson(),
        "MBL": mbl.toJson(),
        "MXC": mxc.toJson(),
        "FCT2": fct2.toJson(),
        "WOM": wom.toJson(),
        "BOA": boa.toJson(),
        "MEV": mev.toJson(),
        "SXP": sxp.toJson(),
        "COS": cos.toJson(),
        "EL": el.toJson(),
        "HIVE": hive.toJson(),
        "XPR": xpr.toJson(),
        "VRA": vra.toJson(),
        "FIT": fit.toJson(),
        "EGG": egg.toJson(),
        "BORA": bora.toJson(),
        "ARPA": arpa.toJson(),
        "CTC": ctc.toJson(),
        "APM": apm.toJson(),
        "CKB": ckb.toJson(),
        "AERGO": aergo.toJson(),
        "EVZ": evz.toJson(),
        "QTCON": qtcon.toJson(),
        "UNI": uni.toJson(),
        "YFI": yfi.toJson(),
        "UMA": uma.toJson(),
        "AAVE": aave.toJson(),
        "COMP": comp.toJson(),
        "BAL": bal.toJson(),
        "RSR": rsr.toJson(),
        "NMR": nmr.toJson(),
        "RLC": rlc.toJson(),
        "UOS": uos.toJson(),
        "SAND": sand.toJson(),
        "STPT": stpt.toJson(),
        "BEL": bel.toJson(),
        "OBSR": obsr.toJson(),
        "POLA": pola.toJson(),
        "ADP": adp.toJson(),
        "DVI": dvi.toJson(),
        "GHX": ghx.toJson(),
        "MVC": mvc.toJson(),
        "BLY": bly.toJson(),
        "GRT": grt.toJson(),
        "BIOT": biot.toJson(),
        "SNX": snx.toJson(),
        "SOFI": sofi.toJson(),
        "GRACY": gracy.toJson(),
        "OXT": oxt.toJson(),
        "MAP": map.toJson(),
        "AQT": aqt.toJson(),
        "WIKEN": wiken.toJson(),
        "CTSI": ctsi.toJson(),
        "MANA": mana.toJson(),
        "LPT": lpt.toJson(),
        "MKR": mkr.toJson(),
        "SUSHI": sushi.toJson(),
        "ASM": asm.toJson(),
        "PUNDIX": pundix.toJson(),
        "CELR": celr.toJson(),
        "FRONT": front.toJson(),
        "RLY": rly.toJson(),
        "OCEAN": ocean.toJson(),
        "BFC": bfc.toJson(),
        "ALICE": alice.toJson(),
        "OGN": ogn.toJson(),
        "COTI": coti.toJson(),
        "CAKE": cake.toJson(),
        "BNT": bnt.toJson(),
        "XVS": xvs.toJson(),
        "SWAP": swap.toJson(),
        "CHZ": chz.toJson(),
        "AXS": axs.toJson(),
        "DAO": dao.toJson(),
        "SIX": six.toJson(),
        "DAI": dai.toJson(),
        "SHIB": shib.toJson(),
        "MATIC": matic.toJson(),
        "WOO": woo.toJson(),
        "ACH": ach.toJson(),
        "XLM": xlm.toJson(),
        "ONT": ont.toJson(),
        "META": meta.toJson(),
        "KLAY": klay.toJson(),
        "ONG": ong.toJson(),
        "ALGO": algo.toJson(),
        "JST": jst.toJson(),
        "XTZ": xtz.toJson(),
        "MLK": mlk.toJson(),
        "DOT": dot.toJson(),
        "ATOM": atom.toJson(),
        "TEMCO": temco.toJson(),
        "DOGE": doge.toJson(),
        "KSM": ksm.toJson(),
        "CTK": ctk.toJson(),
        "BNB": bnb.toJson(),
        "NFT": nft.toJson(),
        "SUN": sun.toJson(),
        "XEC": xec.toJson(),
        "AGIX": agix.toJson(),
        "SOL": sol.toJson(),
        "FNSA": fnsa.toJson(),
        "EGLD": egld.toJson(),
        "MASK": mask.toJson(),
        "C98": c98.toJson(),
        "MED": med.toJson(),
        "1INCH": the1Inch.toJson(),
        "CRV": crv.toJson(),
        "BOBA": boba.toJson(),
        "DYDX": dydx.toJson(),
        "MINA": mina.toJson(),
        "FLOW": flow.toJson(),
        "JOE": joe.toJson(),
        "GALA": gala.toJson(),
        "BTT": btt.toJson(),
        "JASMY": jasmy.toJson(),
        "REQ": req.toJson(),
        "CSPR": cspr.toJson(),
        "AVAX": avax.toJson(),
        "TDROP": tdrop.toJson(),
        "HBAR": hbar.toJson(),
        "FANC": fanc.toJson(),
        "NPT": npt.toJson(),
        "REI": rei.toJson(),
        "T": t.toJson(),
        "MBX": mbx.toJson(),
        "GMT": gmt.toJson(),
        "TAVA": tava.toJson(),
        "DAR": dar.toJson(),
        "APE": ape.toJson(),
        "WNCG": wncg.toJson(),
        "ALT": alt.toJson(),
        "XCN": xcn.toJson(),
        "AZIT": azit.toJson(),
        "FLR": flr.toJson(),
        "SFP": sfp.toJson(),
        "FITFI": fitfi.toJson(),
        "STAT": stat.toJson(),
        "CRTS": crts.toJson(),
        "VIX": vix.toJson(),
        "LBL": lbl.toJson(),
        "FLZ": flz.toJson(),
        "LM": lm.toJson(),
        "GRND": grnd.toJson(),
        "APT": apt.toJson(),
        "BLUR": blur.toJson(),
        "WEMIX": wemix.toJson(),
        "OAS": oas.toJson(),
        "HOOK": hook.toJson(),
        "ENTC": entc.toJson(),
        "ONIT": onit.toJson(),
        "OP": op.toJson(),
        "ROA": roa.toJson(),
        "GMX": gmx.toJson(),
        "STX": stx.toJson(),
        "XPLA": xpla.toJson(),
        "ARB": arb.toJson(),
        "INJ": inj.toJson(),
        "HFT": hft.toJson(),
        "RPL": rpl.toJson(),
        "IMX": imx.toJson(),
        "CFX": cfx.toJson(),
        "ACS": acs.toJson(),
        "FXS": fxs.toJson(),
        "CELO": celo.toJson(),
        "LDO": ldo.toJson(),
        "FTM": ftm.toJson(),
        "FET": fet.toJson(),
        "SUI": sui.toJson(),
        "NCT": nct.toJson(),
        "FLOKI": floki.toJson(),
        "ALEX": alex.toJson(),
        "ID": id.toJson(),
        "RNDR": rndr.toJson(),
        "STG": stg.toJson(),
        "OSMO": osmo.toJson(),
        "GAL": gal.toJson(),
        "ILV": ilv.toJson(),
        "MAV": mav.toJson(),
        "RSS3": rss3.toJson(),
        "AUDIO": audio.toJson(),
        "AGI": agi.toJson(),
        "RDNT": rdnt.toJson(),
        "ASTR": astr.toJson(),
        "WLD": wld.toJson(),
        "FLUX": flux.toJson(),
        "RVN": rvn.toJson(),
        "LEVER": lever.toJson(),
        "EDU": edu.toJson(),
        "SEI": sei.toJson(),
        "WAXL": waxl.toJson(),
        "MOC": moc.toJson(),
        "PEPE": pepe.toJson(),
        "CYBER": cyber.toJson(),
        "ARKM": arkm.toJson(),
        "PYR": pyr.toJson(),
        "IOTX": iotx.toJson(),
        "HIGH": high.toJson(),
        "PENDLE": pendle.toJson(),
        "STORJ": storj.toJson(),
        "API3": api3.toJson(),
        "ZTX": ztx.toJson(),
        "MNT": mnt.toJson(),
        "GTC": gtc.toJson(),
        "TIA": tia.toJson(),
        "ZBC": zbc.toJson(),
        "SPURS": spurs.toJson(),
        "NEO": neo.toJson(),
        "GAS": gas.toJson(),
        "HIFI": hifi.toJson(),
        "BIGTIME": bigtime.toJson(),
        "GRS": grs.toJson(),
        "ARK": ark.toJson(),
        "YGG": ygg.toJson(),
        "HUNT": hunt.toJson(),
        "KAVA": kava.toJson(),
        "STMX": stmx.toJson(),
        "MAGIC": magic.toJson(),
        "USDT": usdt.toJson(),
        "USDC": usdc.toJson(),
        "RAD": rad.toJson(),
        "LSK": lsk.toJson(),
        "TT": tt.toJson(),
        "ACE": ace.toJson(),
        "IQ": iq.toJson(),
        "PYTH": pyth.toJson(),
        "MANTA": manta.toJson(),
        "JUP": jup.toJson(),
        "STRK": strk.toJson(),
        "SC": sc.toJson(),
        "STRAX": strax.toJson(),
        "date": date,
      };
}

class The1Inch {
  String openingPrice;
  String closingPrice;
  String minPrice;
  String maxPrice;
  String unitsTraded;
  String accTradeValue;
  String prevClosingPrice;
  String unitsTraded24H;
  String accTradeValue24H;
  String fluctate24H;
  String fluctateRate24H;

  The1Inch({
    required this.openingPrice,
    required this.closingPrice,
    required this.minPrice,
    required this.maxPrice,
    required this.unitsTraded,
    required this.accTradeValue,
    required this.prevClosingPrice,
    required this.unitsTraded24H,
    required this.accTradeValue24H,
    required this.fluctate24H,
    required this.fluctateRate24H,
  });

  factory The1Inch.fromJson(Map<String, dynamic> json) => The1Inch(
        openingPrice: json["opening_price"],
        closingPrice: json["closing_price"],
        minPrice: json["min_price"],
        maxPrice: json["max_price"],
        unitsTraded: json["units_traded"],
        accTradeValue: json["acc_trade_value"],
        prevClosingPrice: json["prev_closing_price"],
        unitsTraded24H: json["units_traded_24H"],
        accTradeValue24H: json["acc_trade_value_24H"],
        fluctate24H: json["fluctate_24H"],
        fluctateRate24H: json["fluctate_rate_24H"],
      );

  Map<String, dynamic> toJson() => {
        "opening_price": openingPrice,
        "closing_price": closingPrice,
        "min_price": minPrice,
        "max_price": maxPrice,
        "units_traded": unitsTraded,
        "acc_trade_value": accTradeValue,
        "prev_closing_price": prevClosingPrice,
        "units_traded_24H": unitsTraded24H,
        "acc_trade_value_24H": accTradeValue24H,
        "fluctate_24H": fluctate24H,
        "fluctate_rate_24H": fluctateRate24H,
      };
}
